### ISSUE TITLE
Error when Building (Catalina) Cannot find file "delta-core"

### ISSUE THREAD

**Issue by hellomynameisaaaaaaaaaaaaa** [stackotter/delta-client#4]
Error log:

CpResource /Users/guest/Downloads/delta-core /Users/guest/Library/Developer/Xcode/DerivedData/DeltaClient-chttwycariivqtechoycnufudlgi/Build/Products/Release/DeltaClient.app/Contents/Resources/delta-core (in target 'DeltaClient (macOS)' from project 'DeltaClient')
    cd /Users/guest/Downloads/delta-client-main
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/guest/Downloads/delta-core /Users/guest/Library/Developer/Xcode/DerivedData/DeltaClient-chttwycariivqtechoycnufudlgi/Build/Products/Release/DeltaClient.app/Contents/Resources

error: /Users/guest/Downloads/delta-core: No such file or directory (in target 'DeltaClient (macOS)' from project 'DeltaClient')

Running MacOS 10.15.7, 16GB Memory

**Comment by stackotter** [comment]
How are you building the app? I'm confused why you've also manually downloaded delta core. Is that so that you can change the delta core minimum platform to Catalina (from memory it's currently Big Sur)? If so, what steps did you take to setup the environment before building? Did you just drag delta core into the file navigator of the delta client project?

**Comment by stackotter** [comment]
Do you still want to try and build for Catalina or can I close this issue?

**Comment by stackotter** [comment]
For anyone reading this thread, it's currently not possible to build Delta Client for anything earlier than Big Sur because it uses SwiftUI features that aren't available on earlier OSes. Feel free to try and add Catalina compatibility using compiler directives to add alternatives, but for now I'm just going to close this issue.

**Comment by stackotter** [comment]
Although, I just realised that delta core may be able to run on earlier OSes cause it doesn't use any newer features anymore as far as I know (all the SwiftUI code has been moved to delta client). Eventually I might even move away from SwiftUI so that the UI can be themed with CSS or something.
