### ISSUE TITLE
Provide a way to perform Frame Capture automatically via shortcut / button.

### ISSUE THREAD

**Issue by JezewskiG** [stackotter/delta-client#85]
**Is your feature request related to a problem? Please describe.**
Given the current level of project development and active rendering work, the opportunity to receive debug data from users seems significant. Unfortunately, not every user has the opportunity / ability to obtain such data.

**Describe the solution you'd like**
The goal, is to provide clear and concise way of capturing debugging information using Metal Debugger programatically. The action could be triggered by a simple, non-obstructive keyboard shortcut or a button in the menu.

**Describe alternatives you've considered**
The only alternative is relying on user to capture the debugging information, which requires Xcode IDE. This significantly limits the pool of users who can provide such data.

**Additional context**
Frame Capture Debugging Tools provide the means to introduce such feature without impact on performance.

_Suggestions for keyboard shortcuts welcome in the discussion._

**Comment by stackotter** [comment]
In Vanilla minecraft all of the debug commands are f3+[some other key]. Maybe the keyboard shortcut for performing a frame capture could be something like f3+e (all of the letters that make sense to me are used by existing vanilla commands).

Another option would be doing a similar thing but using another function key for delta client only commands, so that it's clear which ones are delta client specific and which ones are in vanilla too. Perhaps f4+g?

**Comment by stackotter** [comment]
I've implemented in-app gpu frame capture, the default key bind is `;` but it can easily be changed (key combinations aren't supported yet)
